version: '3'
services:

  # web:
  #   build: ./web
  #   restart: always
  #   volumes:
  #     - ./web:/var/www/html:ro
  #   environment:
  #     - VIRTUAL_HOST=ggqq.tk
  #     - LETSENCRYPT_HOST=ggqq.tk
  #   depends_on:
  #     - proxy
  #     - letsencrypt-companion
  #   networks:
  #     - proxy-tier
  #     - default

  # test with grafana
  web:
    image: grafana/grafana
    environment:
      - VIRTUAL_HOST=ggqq.tk
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=ggqq.tk
    depends_on:
      - nginx-proxy
      - nginx-proxy-acme

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    # networks:
    #   - proxy-tier

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # networks:
    #   - proxy-tier
    depends_on:
      - proxy

volumes:
  certs:
  acme:
  vhost.d:
  html:

# networks:
#   proxy-tier: