version: '3'
services:

  plweb:
    image: nginx:alpine
    restart: always
    volumes:
      - ./plweb/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./plweb/503.html:/usr/share/nginx/html/503.html:ro
      - ./plweb/502.html:/usr/share/nginx/html/502.html:ro  
      # - playlistenerwebassets:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=moog.tk
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=moog.tk
    networks:
      - proxy-tier
      - playlistener-network
    depends_on:
      - nginx-proxy
      - nginx-proxy-acme

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - nginx-proxy

volumes:
  certs:
  acme:
  vhost.d:
  html:

  # playlistenerwebassets:
  #   external: true

networks:
  proxy-tier:
  playlistener-network:
    external: true
    driver: bridge
    name: playlistener-network